site_name: Orchard Core Documentation
theme:
  name: 'material'
  logo: 'docs/assets/images/orchard-logo.png'
  favicon: 'docs/assets/images/favicon.png'
  feature:
    tabs: true
  palette:
    primary: 'blue'
    accent: 'light blue'
  static_templates:
    - 404.html
    
extra:
  social:
    - type: 'leaf'
      link: 'https://orchardcore.net'
    - type: 'github-alt'
      link: 'https://github.com/OrchardCMS/OrchardCore'
    - type: 'twitter'
      link: 'https://twitter.com/OrchardCMS'

# Repository
repo_name: OrchardCMS/OrchardCore
repo_url: https://github.com/OrchardCMS/OrchardCore
edit_uri: edit/dev/src/

# Options
docs_dir: src

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.superfences
  - toc:
      permalink: true
#  - markdown.extensions.nl2br

plugins:
  - search
  - git-revision-date-localized
  
# Page tree
nav:
    - About Orchard Core: README.md
    - Getting started: 
        - Create a CMS Web application: docs/getting-started/README.md
        - Recipes and Starter Themes: docs/getting-started/starter-recipes.md
        - Code Generation Templates: docs/getting-started/templates/README.md
        - Create a Theme: docs/getting-started/theme.md
    - Glossary: 
        - Terms and Concepts: docs/glossary/README.md
    - How-to guides: 
        - Follow the Guides: docs/guides/README.md
        - Create a modular application: docs/guides/create-modular-application-mvc/README.md
        - Create a website: docs/guides/create-cms-application/README.md
        - Create a Decoupled CMS site: docs/guides/decoupled-cms/README.md
        - Add an admin menu: docs/guides/add-admin-menu/README.md
        - Implement Full Text search: docs/guides/implement-fulltext-search/README.md
        - Install localization files: docs/guides/install-localization-files/README.md
        - Integrate Facebook plugins: docs/guides/integrate-facebook-plugins/README.md
        - Run code on startup: docs/guides/run-code-on-startup/README.md
        - Create a custom admin theme: docs/guides/create-admin-theme/README.md
    - Key Topics: 
        - Manage your Content: docs/topics/content-management/README.md
        - Customize the Display: docs/topics/display/README.md
        - Localize your site: docs/topics/localize/README.md
        - Handle the Media: docs/topics/media/README.md
        - Navigate between pages: docs/topics/navigation/README.md
        - Query and Search data: docs/topics/search/README.md
        - Secure your application: docs/topics/security/README.md
#        - Data: docs/topics/data/README.md
#        - Configuration: docs/topics/configuration/README.md
        - Workflows: docs/topics/workflows/README.md
    - Reference: 
        - CMS Modules: 
            - Content Types: docs/reference/modules/ContentTypes/README.md
            - Content Parts: 
                - Add Parts to your Content: docs/reference/modules/ContentParts/README.md
                - Title: docs/reference/modules/Title/README.md
                - Autoroute: docs/reference/modules/Autoroute/README.md
                - Alias: docs/reference/modules/Alias/README.md
                - Html: docs/reference/modules/Html/README.md
                - Markdown: docs/reference/modules/Markdown/README.md
                - List: docs/reference/modules/List/README.md
                - Flow: docs/reference/modules/Flow/README.md 
                - Bag: docs/reference/modules/Flow/BagPart.md        
            - Content Fields: docs/reference/modules/ContentFields/README.md
            - Content Preview: docs/reference/modules/ContentPreview/README.md
            - Content Localization: docs/reference/modules/ContentLocalization/README.md
            - Layers: docs/reference/modules/Layers/README.md
            - Widgets: docs/reference/modules/Widgets/README.md
            - Forms: docs/reference/modules/Forms/README.md
            - Templates: docs/reference/modules/Templates/README.md
            - Themes: docs/reference/modules/Themes/README.md
            - Liquid: docs/reference/modules/Liquid/README.md
            - Indexing: docs/reference/modules/Indexing/README.md
            - SQL: docs/reference/modules/SQL/README.md
            - Lucene: docs/reference/modules/Lucene/README.md
            - Queries: docs/reference/modules/Queries/README.md
            - Media: docs/reference/modules/Media/README.md
            - Media Azure: docs/reference/modules/Media.Azure/README.md
            - ReCaptcha: docs/reference/modules/ReCaptcha/README.md
            - Resources: docs/reference/modules/Resources/README.md
            - Sitemaps: docs/reference/modules/Sitemaps/README.md
            - Menu: docs/reference/modules/Menu/README.md
            - Navigation: docs/reference/modules/Navigation/README.md
            - Admin: docs/reference/modules/Admin/README.md
            - Admin Menu: docs/reference/modules/AdminMenu/README.md
            - Taxonomies: docs/reference/modules/Taxonomies/README.md
            - Authentication:
                - Microsoft: docs/reference/modules/Microsoft.Authentication/README.md
                - Facebook: docs/reference/modules/Facebook/README.md
                - Twitter: docs/reference/modules/Twitter/README.md
                - GitHub: docs/reference/modules/GitHub/README.md
                - Google: docs/reference/modules/Google/README.md
        - Core Modules: 
    #        - How to use Core Modules: docs/reference/core/README.md
            - Features: docs/reference/modules/Features/README.md
            - Contents: docs/reference/modules/Contents/README.md
            - Configuration: docs/reference/core/Configuration/README.md
            - Custom Settings: docs/reference/modules/CustomSettings/README.md
            - Placement: docs/reference/core/Placement/README.md
            - Data: docs/reference/core/Data/README.md
            - Dynamic Cache: docs/reference/modules/DynamicCache/README.md
            - Email: docs/reference/modules/Email/README.md
            - GraphQL: docs/reference/modules/Apis.GraphQL/README.md
            - GraphQL queries: docs/reference/core/Apis.GraphQL.Abstractions/README.md
            - Health Check: docs/reference/modules/HealthChecks/README.md
            - Localization: docs/reference/modules/Localize/README.md
            - Logging Serilog: docs/reference/core/Logging.Serilog/readme.md
            - Modules: docs/reference/core/Modules/README.md
            - OpenId: docs/reference/modules/OpenId/README.md
            - Razor Helpers: docs/reference/core/Razor/README.md
            - Recipes: docs/reference/modules/Recipes/README.md
            - Roles: docs/reference/modules/Roles/README.md
            - Scripting: docs/reference/modules/Scripting/README.md
            - Setup: docs/reference/modules/Setup/README.md
            - Shells: docs/reference/core/Shells/README.md
            - Tenants: docs/reference/modules/Tenants/README.md
            - Workflows: docs/reference/modules/Workflows/README.md
            - DataProtection (Azure Storage): docs/reference/modules/DataProtection.Azure/README.md
    - Resources: 
        - Learning: docs/resources/README.md
        - Workshops: docs/resources/workshops/README.md
    