site_name: Orchard Core Documentation
theme: readthedocs

# Repository
repo_name: OrchardCMS/OrchardCore
repo_url: https://github.com/OrchardCMS/OrchardCore

# Options
docs_dir: src

extra_css: 
- docs/css/code-tabs.css
- docs/css/extra.css

extra_javascript:
- docs/js/extra.js

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
#  - markdown.extensions.nl2br
#  - markdown_fenced_code_tabs

# Page tree
pages:
    - About Orchard Core: index.md
    - Getting started:
        - Create a CMS Web application: docs/getting-started/README.md
        - Create a Theme: docs/getting-started/theme.md
    - Code Generation Templates: docs/templates/README.md
    - Orchard Core Modules: OrchardCore/OrchardCore/Modules/README.md
    - CMS Modules:
        - Title: OrchardCore.Modules/OrchardCore.Title/README.md
        - Alias: OrchardCore.Modules/OrchardCore.Alias/README.md
        - Autoroute: OrchardCore.Modules/OrchardCore.Autoroute/README.md
        - Html: OrchardCore.Modules/OrchardCore.Html/README.md
        - Contents: OrchardCore.Modules/OrchardCore.Contents/README.md
        - Content Fields: OrchardCore.Modules/OrchardCore.ContentFields/README.md
        - Content Preview: OrchardCore.Modules/OrchardCore.ContentPreview/README.md
        - Content Types: OrchardCore.Modules/OrchardCore.ContentTypes/README.md
        - Lists: OrchardCore.Modules/OrchardCore.Lists/README.md
        - Markdown: OrchardCore.Modules/OrchardCore.Markdown/README.md
        - Media: OrchardCore.Modules/OrchardCore.Media/README.md
        - Menu: OrchardCore.Modules/OrchardCore.Menu/README.md
        - Navigation: OrchardCore.Modules/OrchardCore.Navigation/README.md
        - Indexing: OrchardCore.Modules/OrchardCore.Indexing/README.md
        - Lucene: OrchardCore.Modules/OrchardCore.Lucene/README.md
        - Queries: OrchardCore.Modules/OrchardCore.Queries/README.md
        - Templates: OrchardCore.Modules/OrchardCore.Templates/README.md
        - Themes: OrchardCore.Modules/OrchardCore.Themes/README.md
        - Liquid: OrchardCore.Modules/OrchardCore.Liquid/README.md
        - Custom Settings: OrchardCore.Modules/OrchardCore.CustomSettings/README.md
        - Widgets: OrchardCore.Modules/OrchardCore.Widgets/README.md
        - Flows: OrchardCore.Modules/OrchardCore.Flows/README.md
        - Forms: OrchardCore.Modules/OrchardCore.Forms/README.md
    - Core Modules:
        - Placement: OrchardCore/OrchardCore.DisplayManagement/README.md
        - Dynamic Cache: OrchardCore.Modules/OrchardCore.DynamicCache/README.md
        - Localization: OrchardCore.Modules/OrchardCore.Localization/README.md
        - Logging Serilog: OrchardCore/OrchardCore.Logging.Serilog/readme.md
        - OpenId: OrchardCore.Modules/OrchardCore.OpenId/README.md
        - Recipes: OrchardCore.Modules/OrchardCore.Recipes/README.md
        - Resources: OrchardCore.Modules/OrchardCore.Resources/README.md
        - Roles: OrchardCore.Modules/OrchardCore.Roles/README.md
        - Scripting: OrchardCore.Modules/OrchardCore.Scripting/README.md
        - Setup: OrchardCore.Modules/OrchardCore.Setup/README.md
        - Tenants: OrchardCore.Modules/OrchardCore.Tenants/README.md
        - Workflows: OrchardCore.Modules/OrchardCore.Workflows/README.md
        - DataProtection (Azure Storage): OrchardCore.Modules/OrchardCore.DataProtection.Azure/README.md