blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/OrchardCMS/OrchardCore/discussions/new
    about: Is your issue perhaps more of a discussion? Please open topics for discussion using the new GitHub Discussions feature.