# Labels PRs without updates for 60 days as stale, then closes them 15 days later.
name: Close stale PRs

on:
  pull_request:
  schedule:
    # Every day at 1:39 AM UTC. A random time to avoid GitHub Actions being overloaded by scheduled workflows.
    - cron: '39 1 * * *'

jobs:
  close-stale-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: >
            It seems that this pull request didn't really move for quite a while. Is this something you'd like to 
            revisit any time soon or should we close?
          stale-pr-label: stale
          # Not marking issues as stale.
          days-before-issue-stale: -1
          # Close the PR 15 days after marking it as stale.
          days-before-close: 15
          close-pr-message: >
            Closing this pull request because it has been stale for very long. If you think this is still relevant, 
            feel free to reopen it.
