name: Validating Building the Documentation

on: 
  push:
    paths:
      - 'mkdocs.yml'
      - 'src/docs/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'mkdocs.yml'
      - 'src/docs/**'

concurrency:
  group: ${{ github.head_ref || github.run_id }}-docs_validation
  cancel-in-progress: true

jobs:
  validate-building-documentation:
    name: Validating Building the Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Necessary to avoid mkdocs-git-revision-date-localized-plugin warnings.
        fetch-depth: 0

    - name: Install Dependencies
      # Installing pip v22.0.3 is only necessary because unbuntu-latest runners include v22.0.2, which has a bug. See:
      # https://github.com/actions/runner-images/issues/9731. That line can be removed once the runners are updated.
      run: |
        python -m pip install pip==22.0.3
        pip install -r src/docs/requirements.txt -v

    - name: Build Documentation
      run: python -m mkdocs build --strict
